version: '3.8'

services:
  web:
    container_name: web
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./:/app
    ports:
      - '3004:3004'
    tty: true
    environment:
      NODE_ENV: development